In [11]:
import pandas as pd 
# pandas is a Python package providing fast, flexible, and expressive data structures designed to make working with “relational” or “labeled” data both easy and intuitive. It aims to be the fundamental high-level building block for doing practical, real-world data analysis in Python.

In [12]:
df = pd.read_csv("titanic.csv")
# read_csv is used to load a CSV file as a pandas dataframe

In [13]:
data = df.notnull()
# notnull is a pandas function that will examine one or multiple values to validate that they are not null.

In [14]:
df = df.where(data).dropna()
# The dropna() method removes the rows that contains NULL values. The dropna() method returns a new DataFrame object unless the inplace parameter is set to True , in that case the dropna() method does the removing in the original DataFrame instead.

In [15]:
average_age = df["Age"].mean()
# The mean() function is used to return the mean of the values for the requested axis.

In [16]:
average_age

35.6744262295082